// Generated by Firebase AI SDK Generator for Web (TypeScript 5.x)
// DO NOT EDIT DIRECTLY - Modify Jinja2 templates instead.

export type BackendTarget = 'googleAI' | { agentPlatform: { location?: string } };

export interface InteractionsBackendConfig {
  target?: BackendTarget;
  projectId?: string;
  useProxy?: boolean;
  customBaseUrl?: string;
}

export class BackendResolver {
  readonly target: BackendTarget;
  readonly projectId?: string;
  readonly useProxy: boolean;
  readonly customBaseUrl?: string;
  readonly apiKey: string;
  readonly appCheckToken?: string;
  readonly authToken?: string;
  readonly clientVersion: string;

  static readonly GOOGLE_AI_DIRECT_BASE = 'https://generativelanguage.googleapis.com';
  static readonly FIREBASE_PROXY_BASE = 'https://firebasevertexai.googleapis.com';

  constructor(options: {
    config?: InteractionsBackendConfig;
    apiKey: string;
    appCheckToken?: string;
    authToken?: string;
    clientVersion?: string;
    customBaseUrl?: string;
  }) {
    this.target = options.config?.target ?? 'googleAI';
    this.projectId = options.config?.projectId;
    this.useProxy = options.config?.useProxy ?? false;
    this.customBaseUrl = options.customBaseUrl ?? options.config?.customBaseUrl;
    this.apiKey = options.apiKey;
    this.appCheckToken = options.appCheckToken;
    this.authToken = options.authToken;
    this.clientVersion = options.clientVersion ?? 'fire-ai-web/1.0.0';
  }

  resolveEndpoint(stream = false): string {
    const query = stream ? '?alt=sse' : '';

    if (this.customBaseUrl) {
      const base = this.customBaseUrl.replace(/\/+$/, '');
      if (typeof this.target === 'object' && 'agentPlatform' in this.target) {
        const loc = this.target.agentPlatform.location ?? 'global';
        const project = this.projectId ?? 'default-project';
        return `${base}/v1beta/projects/${project}/locations/${loc}/interactions${query}`;
      }
      return `${base}/v1beta/interactions${query}`;
    }

    if (this.useProxy) {
      const project = this.projectId ?? 'default-project';
      if (typeof this.target === 'object' && 'agentPlatform' in this.target) {
        const loc = this.target.agentPlatform.location ?? 'global';
        return `${BackendResolver.FIREBASE_PROXY_BASE}/v1beta/projects/${project}/locations/${loc}/interactions${query}`;
      }
      return `${BackendResolver.FIREBASE_PROXY_BASE}/v1beta/projects/${project}/interactions${query}`;
    }

    if (typeof this.target === 'object' && 'agentPlatform' in this.target) {
      const loc = this.target.agentPlatform.location ?? 'global';
      const project = this.projectId ?? 'default-project';
      const host = loc === 'global' ? 'https://aiplatform.googleapis.com' : `https://${loc}-aiplatform.googleapis.com`;
      return `${host}/v1beta/projects/${project}/locations/${loc}/interactions${query}`;
    }

    return `${BackendResolver.GOOGLE_AI_DIRECT_BASE}/v1beta/interactions${query}`;
  }

  resolveHeaders(isStream = false): Record<string, string> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json; charset=utf-8',
      'X-Firebase-Client': this.clientVersion,
      'X-Goog-Api-Client': `gl-js/ESM ${this.clientVersion}`,
    };

    if (isStream) {
      headers['Accept'] = 'text/event-stream';
      headers['Cache-Control'] = 'no-cache';
    }

    if (this.target === 'googleAI' && this.apiKey) {
      headers['x-goog-api-key'] = this.apiKey;
    }

    if (this.authToken) {
      headers['Authorization'] = `Bearer ${this.authToken}`;
    }

    if (this.appCheckToken) {
      headers['X-Firebase-AppCheck'] = this.appCheckToken;
    }

    return headers;
  }
}