// Generated by Firebase AI SDK Generator for Web (TypeScript 5.x)
// DO NOT EDIT DIRECTLY - Modify Jinja2 templates instead.

import type { Interaction } from '../types/internal/interaction';
import type { Step, StepDelta } from '../types/internal/step';

export type InteractionErrorCategory =
  | 'api_error'
  | 'generation_blocked'
  | 'generation_error'
  | 'unknown';

export type InteractionErrorCode =
  | 'invalid_request'
  | 'failed_precondition'
  | 'out_of_range'
  | 'parameter_unknown'
  | 'authentication'
  | 'permission_denied'
  | 'not_found'
  | 'model_not_found'
  | 'already_exists'
  | 'aborted'
  | 'rate_limit_exceeded'
  | 'quota_exceeded'
  | 'too_many_requests'
  | 'cancelled'
  | 'api_error'
  | 'unimplemented'
  | 'service_unavailable'
  | 'deadline_exceeded'
  | 'safety'
  | 'recitation'
  | 'language'
  | 'prohibited_content'
  | 'spii'
  | 'blocklist'
  | 'image_safety'
  | 'image_prohibited_content'
  | 'image_recitation'
  | 'image_other'
  | 'content_blocked'
  | 'malformed_function_call'
  | 'malformed_tool_call'
  | 'unexpected_tool_call'
  | 'no_image'
  | 'too_many_tool_calls'
  | 'missing_thought_signature'
  | (string & {});

const GENERATION_BLOCKED_CODES = new Set<string>([
  'safety',
  'recitation',
  'language',
  'prohibited_content',
  'spii',
  'blocklist',
  'image_safety',
  'image_prohibited_content',
  'image_recitation',
  'image_other',
  'content_blocked',
]);

const GENERATION_ERROR_CODES = new Set<string>([
  'malformed_function_call',
  'malformed_tool_call',
  'unexpected_tool_call',
  'no_image',
  'too_many_tool_calls',
  'missing_thought_signature',
]);

const API_ERROR_CODES = new Set<string>([
  'invalid_request',
  'failed_precondition',
  'out_of_range',
  'parameter_unknown',
  'authentication',
  'permission_denied',
  'not_found',
  'model_not_found',
  'already_exists',
  'aborted',
  'rate_limit_exceeded',
  'quota_exceeded',
  'too_many_requests',
  'cancelled',
  'api_error',
  'unimplemented',
  'service_unavailable',
  'deadline_exceeded',
]);

const RETRYABLE_CODES = new Set<string>([
  'rate_limit_exceeded',
  'too_many_requests',
  'service_unavailable',
  'deadline_exceeded',
  'aborted',
  'api_error',
]);

export function categorizeErrorCode(code: string): InteractionErrorCategory {
  if (GENERATION_BLOCKED_CODES.has(code)) return 'generation_blocked';
  if (GENERATION_ERROR_CODES.has(code)) return 'generation_error';
  if (API_ERROR_CODES.has(code)) return 'api_error';
  return 'unknown';
}

export function statusToSnakeCase(httpStatus: number): string {
  switch (httpStatus) {
    case 400: return 'invalid_request';
    case 401: return 'authentication';
    case 403: return 'permission_denied';
    case 404: return 'not_found';
    case 409: return 'already_exists';
    case 416: return 'out_of_range';
    case 429: return 'rate_limit_exceeded';
    case 499: return 'cancelled';
    case 500: return 'api_error';
    case 501: return 'unimplemented';
    case 503: return 'service_unavailable';
    case 504: return 'deadline_exceeded';
    default: return 'unknown';
  }
}

export class InteractionsError extends Error {
  readonly code: InteractionErrorCode;
  readonly category: InteractionErrorCategory;
  readonly httpStatus?: number;
  readonly isRetryable: boolean;
  readonly isBlocked: boolean;

  constructor(code: InteractionErrorCode, message: string, httpStatus?: number) {
    const statusInfo = httpStatus ? ` [${httpStatus}]` : '';
    super(`Interactions request failed${statusInfo} (${code}): ${message}`);
    this.name = 'InteractionsError';
    this.code = code;
    this.category = categorizeErrorCode(code);
    this.httpStatus = httpStatus;
    this.isRetryable = RETRYABLE_CODES.has(code);
    this.isBlocked = this.category === 'generation_blocked';
  }
}

export function parseInteractionsError(httpStatus: number, bodyText: string): InteractionsError {
  try {
    const parsed = JSON.parse(bodyText) as Record<string, unknown>;
    const errObj = (parsed.error as Record<string, unknown>) || parsed;
    if (errObj && typeof errObj === 'object') {
      const code = typeof errObj.code === 'string' && errObj.code.length > 0
        ? errObj.code
        : statusToSnakeCase(httpStatus);
      const message = typeof errObj.message === 'string' && errObj.message.length > 0
        ? errObj.message
        : bodyText;
      return new InteractionsError(code, message, httpStatus);
    }
  } catch {
    // Non-JSON error response fallback
  }
  return new InteractionsError(statusToSnakeCase(httpStatus), bodyText || `HTTP ${httpStatus}`, httpStatus);
}

export interface InteractionStreamingEvent {
  eventType: string;
  interaction?: Interaction;
  step?: Step;
  stepDelta?: StepDelta;
  isDone?: boolean;
  rawJson?: Record<string, unknown>;
}

export async function* decodeSSEStream(
  stream: ReadableStream<Uint8Array>
): AsyncGenerator<InteractionStreamingEvent, void, unknown> {
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  let currentEvent = 'message';

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop() ?? '';

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) {
          // Dispatch block
          currentEvent = 'message';
          continue;
        }

        if (trimmed.startsWith('event:')) {
          currentEvent = trimmed.slice(6).trim();
        } else if (trimmed.startsWith('data:')) {
          const dataString = trimmed.slice(5).trim();
          if (dataString === '[DONE]') {
            yield { eventType: 'done', isDone: true };
            return;
          }

          let json: Record<string, unknown>;
          try {
            json = JSON.parse(dataString) as Record<string, unknown>;
          } catch {
            // Ignore parse errors on comment frames
            continue;
          }

          if (currentEvent === 'error' || json.event_type === 'error' || json.error) {
            const errObj = (json.error as Record<string, unknown>) || json;
            const code = typeof errObj.code === 'string' ? errObj.code : 'api_error';
            const message = typeof errObj.message === 'string' ? errObj.message : 'SSE Stream error';
            throw new InteractionsError(code, message);
          }

          yield {
            eventType: currentEvent,
            interaction: json.interaction as Interaction | undefined,
            step: json.step as Step | undefined,
            stepDelta: json.step_delta as StepDelta | undefined,
            rawJson: json,
          };
        }
      }
    }
  } finally {
    reader.releaseLock();
  }
}