{
    "name": "adhoc",
    "symbols": [
        {
            "name": "deleteObject",
            "classes": [
                "FailRequest",
                "FirebaseStorageError",
                "Location",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "RequestInfo",
                "StorageReference",
                "StorageService",
                "XhrIoPool"
            ],
            "functions": [
                "addAuthHeader_",
                "addGmpidHeader_",
                "addVersionHeader_",
                "appDeleted",
                "canceled",
                "deleteObject",
                "extractBucket",
                "factory",
                "internalError",
                "invalidDefaultBucket",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "lastComponent",
                "makeQueryString",
                "makeRequest",
                "makeUrl",
                "objectErrorHandler",
                "objectNotFound",
                "parent",
                "prependCode",
                "quotaExceeded",
                "registerStorage",
                "retryLimitExceeded",
                "sharedErrorHandler",
                "start",
                "stop",
                "unauthenticated",
                "unauthorized",
                "unknown",
                "validateNumber"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "STORAGE_TYPE",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 12641,
            "sizeWithExtDeps": 17231
        },
        {
            "name": "getDownloadURL",
            "classes": [
                "FailRequest",
                "FirebaseStorageError",
                "Location",
                "Mapping",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "RequestInfo",
                "StorageReference",
                "StorageService",
                "XhrIoPool"
            ],
            "functions": [
                "addAuthHeader_",
                "addGmpidHeader_",
                "addRef",
                "addVersionHeader_",
                "appDeleted",
                "canceled",
                "downloadUrlFromResourceString",
                "downloadUrlHandler",
                "extractBucket",
                "factory",
                "fromResource",
                "fromResourceString",
                "getDownloadURL",
                "getDownloadUrl",
                "getMappings",
                "handlerCheck",
                "internalError",
                "invalidDefaultBucket",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "isNonArrayObject",
                "isString",
                "jsonObjectOrNull",
                "lastComponent",
                "makeQueryString",
                "makeRequest",
                "makeUrl",
                "noDownloadURL",
                "noXform_",
                "objectErrorHandler",
                "objectNotFound",
                "parent",
                "prependCode",
                "quotaExceeded",
                "registerStorage",
                "retryLimitExceeded",
                "sharedErrorHandler",
                "start",
                "stop",
                "unauthenticated",
                "unauthorized",
                "unknown",
                "validateNumber",
                "xformPath"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "STORAGE_TYPE",
                "mappings_",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 14764,
            "sizeWithExtDeps": 19375
        },
        {
            "name": "getMetadata",
            "classes": [
                "FailRequest",
                "FirebaseStorageError",
                "Location",
                "Mapping",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "RequestInfo",
                "StorageReference",
                "StorageService",
                "XhrIoPool"
            ],
            "functions": [
                "addAuthHeader_",
                "addGmpidHeader_",
                "addRef",
                "addVersionHeader_",
                "appDeleted",
                "canceled",
                "extractBucket",
                "factory",
                "fromResource",
                "fromResourceString",
                "getMappings",
                "getMetadata",
                "handlerCheck",
                "internalError",
                "invalidDefaultBucket",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "isNonArrayObject",
                "isString",
                "jsonObjectOrNull",
                "lastComponent",
                "makeQueryString",
                "makeRequest",
                "makeUrl",
                "metadataHandler",
                "noXform_",
                "objectErrorHandler",
                "objectNotFound",
                "parent",
                "prependCode",
                "quotaExceeded",
                "registerStorage",
                "retryLimitExceeded",
                "sharedErrorHandler",
                "start",
                "stop",
                "unauthenticated",
                "unauthorized",
                "unknown",
                "validateNumber",
                "xformPath"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "STORAGE_TYPE",
                "mappings_",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 14247,
            "sizeWithExtDeps": 18854
        },
        {
            "name": "getStorage",
            "classes": [
                "FailRequest",
                "FirebaseStorageError",
                "Location",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "StorageReference",
                "StorageService",
                "XhrIoPool"
            ],
            "functions": [
                "addAuthHeader_",
                "addGmpidHeader_",
                "addVersionHeader_",
                "appDeleted",
                "canceled",
                "extractBucket",
                "factory",
                "getStorage",
                "internalError",
                "invalidDefaultBucket",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "lastComponent",
                "makeQueryString",
                "makeRequest",
                "parent",
                "prependCode",
                "registerStorage",
                "retryLimitExceeded",
                "start",
                "stop",
                "unknown",
                "validateNumber"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "STORAGE_TYPE",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_getProvider",
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 11242,
            "sizeWithExtDeps": 15849
        },
        {
            "name": "list",
            "classes": [
                "FailRequest",
                "FirebaseStorageError",
                "Location",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "RequestInfo",
                "StorageReference",
                "StorageService",
                "XhrIoPool"
            ],
            "functions": [
                "addAuthHeader_",
                "addGmpidHeader_",
                "addVersionHeader_",
                "appDeleted",
                "canceled",
                "extractBucket",
                "factory",
                "fromBackendResponse",
                "fromResponseString",
                "handlerCheck",
                "internalError",
                "invalidDefaultBucket",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "isNonArrayObject",
                "jsonObjectOrNull",
                "lastComponent",
                "list",
                "listHandler",
                "makeQueryString",
                "makeRequest",
                "makeUrl",
                "parent",
                "prependCode",
                "quotaExceeded",
                "registerStorage",
                "retryLimitExceeded",
                "sharedErrorHandler",
                "start",
                "stop",
                "unauthenticated",
                "unauthorized",
                "unknown",
                "validateNumber"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "ITEMS_KEY",
                "PREFIXES_KEY",
                "STORAGE_TYPE",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 13363,
            "sizeWithExtDeps": 17957
        },
        {
            "name": "listAll",
            "classes": [
                "FailRequest",
                "FirebaseStorageError",
                "Location",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "RequestInfo",
                "StorageReference",
                "StorageService",
                "XhrIoPool"
            ],
            "functions": [
                "addAuthHeader_",
                "addGmpidHeader_",
                "addVersionHeader_",
                "appDeleted",
                "canceled",
                "extractBucket",
                "factory",
                "fromBackendResponse",
                "fromResponseString",
                "handlerCheck",
                "internalError",
                "invalidDefaultBucket",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "isNonArrayObject",
                "jsonObjectOrNull",
                "lastComponent",
                "list",
                "list$1",
                "listAll",
                "listAllHelper",
                "listHandler",
                "makeQueryString",
                "makeRequest",
                "makeUrl",
                "parent",
                "prependCode",
                "quotaExceeded",
                "registerStorage",
                "retryLimitExceeded",
                "sharedErrorHandler",
                "start",
                "stop",
                "unauthenticated",
                "unauthorized",
                "unknown",
                "validateNumber"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "ITEMS_KEY",
                "PREFIXES_KEY",
                "STORAGE_TYPE",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 13623,
            "sizeWithExtDeps": 18217
        },
        {
            "name": "ref",
            "classes": [
                "FailRequest",
                "FirebaseStorageError",
                "Location",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "StorageReference",
                "StorageService",
                "XhrIoPool"
            ],
            "functions": [
                "addAuthHeader_",
                "addGmpidHeader_",
                "addVersionHeader_",
                "appDeleted",
                "canceled",
                "child",
                "extractBucket",
                "factory",
                "getChild",
                "internalError",
                "invalidArgument",
                "invalidDefaultBucket",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "isUrl",
                "lastComponent",
                "makeQueryString",
                "makeRequest",
                "noDefaultBucket",
                "parent",
                "prependCode",
                "ref",
                "refFromPath",
                "refFromURL",
                "registerStorage",
                "retryLimitExceeded",
                "start",
                "stop",
                "unknown",
                "validateNumber"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "STORAGE_TYPE",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 12078,
            "sizeWithExtDeps": 16674
        },
        {
            "name": "updateMetadata",
            "classes": [
                "FailRequest",
                "FirebaseStorageError",
                "Location",
                "Mapping",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "RequestInfo",
                "StorageReference",
                "StorageService",
                "XhrIoPool"
            ],
            "functions": [
                "addAuthHeader_",
                "addGmpidHeader_",
                "addRef",
                "addVersionHeader_",
                "appDeleted",
                "canceled",
                "extractBucket",
                "factory",
                "fromResource",
                "fromResourceString",
                "getMappings",
                "handlerCheck",
                "internalError",
                "invalidDefaultBucket",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "isNonArrayObject",
                "isString",
                "jsonObjectOrNull",
                "lastComponent",
                "makeQueryString",
                "makeRequest",
                "makeUrl",
                "metadataHandler",
                "noXform_",
                "objectErrorHandler",
                "objectNotFound",
                "parent",
                "prependCode",
                "quotaExceeded",
                "registerStorage",
                "retryLimitExceeded",
                "sharedErrorHandler",
                "start",
                "stop",
                "toResourceString",
                "unauthenticated",
                "unauthorized",
                "unknown",
                "updateMetadata",
                "validateNumber",
                "xformPath"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "STORAGE_TYPE",
                "mappings_",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 14500,
            "sizeWithExtDeps": 19107
        },
        {
            "name": "uploadBytes",
            "classes": [
                "DataURLParts",
                "FailRequest",
                "FbsBlob",
                "FirebaseStorageError",
                "Location",
                "Mapping",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "RequestInfo",
                "StorageReference",
                "StorageService",
                "StringData",
                "XhrIoPool"
            ],
            "functions": [
                "_nonResumableUpload",
                "addAuthHeader_",
                "addGmpidHeader_",
                "addRef",
                "addVersionHeader_",
                "appDeleted",
                "base64Bytes_",
                "canceled",
                "cannotSliceBlob",
                "dataFromString",
                "dataURLBytes_",
                "dataURLContentType_",
                "determineContentType_",
                "endsWith",
                "extractBucket",
                "factory",
                "fromResource",
                "fromResourceString",
                "getBlob",
                "getBlobBuilder",
                "getMappings",
                "handlerCheck",
                "internalError",
                "invalidDefaultBucket",
                "invalidFormat",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "isNativeBlob",
                "isNativeBlobDefined",
                "isNonArrayObject",
                "isString",
                "jsonObjectOrNull",
                "lastComponent",
                "makeQueryString",
                "makeRequest",
                "makeUrl",
                "metadataForUpload_",
                "metadataHandler",
                "multipartUpload",
                "noXform_",
                "parent",
                "percentEncodedBytes_",
                "prependCode",
                "quotaExceeded",
                "registerStorage",
                "retryLimitExceeded",
                "sharedErrorHandler",
                "sliceBlob",
                "start",
                "stop",
                "toResourceString",
                "unauthenticated",
                "unauthorized",
                "unknown",
                "uploadBytes",
                "utf8Bytes_",
                "validateNumber",
                "xformPath"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "STORAGE_TYPE",
                "StringFormat",
                "mappings_",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 19056,
            "sizeWithExtDeps": 23665
        },
        {
            "name": "uploadBytesResumable",
            "classes": [
                "DataURLParts",
                "FailRequest",
                "FbsBlob",
                "FirebaseStorageError",
                "Location",
                "Mapping",
                "NetworkRequest",
                "NetworkXhrIo",
                "Observer",
                "RequestEndStatus",
                "RequestInfo",
                "ResumableUploadStatus",
                "StorageReference",
                "StorageService",
                "StringData",
                "UploadTask",
                "XhrIoPool"
            ],
            "functions": [
                "addAuthHeader_",
                "addGmpidHeader_",
                "addRef",
                "addVersionHeader_",
                "appDeleted",
                "async",
                "base64Bytes_",
                "canceled",
                "cannotSliceBlob",
                "checkResumeHeader_",
                "continueResumableUpload",
                "createResumableUpload",
                "dataFromString",
                "dataURLBytes_",
                "dataURLContentType_",
                "determineContentType_",
                "endsWith",
                "extractBucket",
                "factory",
                "fromResource",
                "fromResourceString",
                "getBlob",
                "getBlobBuilder",
                "getMappings",
                "getMetadata",
                "getResumableUploadStatus",
                "handlerCheck",
                "internalError",
                "invalidDefaultBucket",
                "invalidFormat",
                "invalidRootOperation",
                "invalidUrl",
                "isFunction",
                "isJustDef",
                "isNativeBlob",
                "isNativeBlobDefined",
                "isNonArrayObject",
                "isString",
                "jsonObjectOrNull",
                "lastComponent",
                "makeQueryString",
                "makeRequest",
                "makeUrl",
                "metadataForUpload_",
                "metadataHandler",
                "multipartUpload",
                "noXform_",
                "objectErrorHandler",
                "objectNotFound",
                "parent",
                "percentEncodedBytes_",
                "prependCode",
                "quotaExceeded",
                "registerStorage",
                "retryLimitExceeded",
                "serverFileWrongSize",
                "sharedErrorHandler",
                "sliceBlob",
                "start",
                "stop",
                "taskStateFromInternalTaskState",
                "toResourceString",
                "unauthenticated",
                "unauthorized",
                "unknown",
                "uploadBytesResumable",
                "utf8Bytes_",
                "validateNumber",
                "xformPath"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "InternalTaskState",
                "STORAGE_TYPE",
                "StringFormat",
                "TaskState",
                "mappings_",
                "name",
                "resumableUploadChunkSize",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 28320,
            "sizeWithExtDeps": 32932
        },
        {
            "name": "uploadString",
            "classes": [
                "DataURLParts",
                "FailRequest",
                "FbsBlob",
                "FirebaseStorageError",
                "Location",
                "Mapping",
                "NetworkRequest",
                "NetworkXhrIo",
                "RequestEndStatus",
                "RequestInfo",
                "StorageReference",
                "StorageService",
                "StringData",
                "XhrIoPool"
            ],
            "functions": [
                "_nonResumableUpload",
                "addAuthHeader_",
                "addGmpidHeader_",
                "addRef",
                "addVersionHeader_",
                "appDeleted",
                "base64Bytes_",
                "canceled",
                "cannotSliceBlob",
                "dataFromString",
                "dataURLBytes_",
                "dataURLContentType_",
                "determineContentType_",
                "endsWith",
                "extractBucket",
                "factory",
                "fromResource",
                "fromResourceString",
                "getBlob",
                "getBlobBuilder",
                "getMappings",
                "handlerCheck",
                "internalError",
                "invalidDefaultBucket",
                "invalidFormat",
                "invalidRootOperation",
                "invalidUrl",
                "isJustDef",
                "isNativeBlob",
                "isNativeBlobDefined",
                "isNonArrayObject",
                "isString",
                "jsonObjectOrNull",
                "lastComponent",
                "makeQueryString",
                "makeRequest",
                "makeUrl",
                "metadataForUpload_",
                "metadataHandler",
                "multipartUpload",
                "noXform_",
                "parent",
                "percentEncodedBytes_",
                "prependCode",
                "quotaExceeded",
                "registerStorage",
                "retryLimitExceeded",
                "sharedErrorHandler",
                "sliceBlob",
                "start",
                "stop",
                "toResourceString",
                "unauthenticated",
                "unauthorized",
                "unknown",
                "uploadString",
                "utf8Bytes_",
                "validateNumber",
                "xformPath"
            ],
            "variables": [
                "CONFIG_STORAGE_BUCKET_KEY",
                "Code",
                "DEFAULT_HOST",
                "DEFAULT_MAX_OPERATION_RETRY_TIME",
                "DEFAULT_MAX_UPLOAD_RETRY_TIME",
                "ErrorCode",
                "STORAGE_TYPE",
                "StringFormat",
                "mappings_",
                "name",
                "version",
                "version$1"
            ],
            "enums": [],
            "externals": {
                "@firebase/app-exp": [
                    "_registerComponent",
                    "registerVersion"
                ],
                "@firebase/util": [
                    "FirebaseError"
                ],
                "@firebase/component": [
                    "Component"
                ]
            },
            "size": 19193,
            "sizeWithExtDeps": 23804
        }
    ]
}