import { spawn } from 'child-process-promise';
import { projectRoot } from '../utils';
import fs from 'fs';
import glob from 'glob';
import { join } from 'path';

const GOOGLE3_HEADER = `
{% comment %}
DO NOT EDIT THIS FILE!
This is generated by the JS SDK team, and any local changes will be
overwritten. Changes should be made in the source code at
https://github.com/firebase/firebase-js-sdk
{% endcomment %}
`;

const tmpDir = `${projectRoot}/temp`;
const PREFERRED_PARAMS = [
  'app',
  'analyticsInstance',
  'appCheckInstance',
  'db',
  'firestore',
  'functionsInstance',
  'installations',
  'messaging',
  'performance',
  'remoteConfig',
  'storage',
  'ai'
];

async function run() {
  const outputFolder = 'docs-devsite';
  const command = 'api-documenter-devsite';

  // Make sure output folder exists
  if (!fs.existsSync(join(projectRoot, outputFolder))) {
    fs.mkdirSync(join(projectRoot, outputFolder), { recursive: true });
  }

  console.log(`Building firestore and generating api-report...`);
  await spawn(
    'yarn',
    [
      'lerna',
      'run',
      '--scope',
      '@firebase/firestore',
      'build'
    ],
    { stdio: 'inherit' }
  );

  await spawn(
    'yarn',
    [
      'lerna',
      'run',
      '--scope',
      '@firebase/firestore',
      'api-report'
    ],
    { stdio: 'inherit' }
  );

  if (fs.existsSync(tmpDir)) {
    console.log(`Removing old json temp dir: ${tmpDir}.`);
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }

  fs.mkdirSync(tmpDir);

  const firestoreTempDir = join(projectRoot, 'packages', 'firestore', 'temp');
  if (fs.existsSync(firestoreTempDir)) {
    const paths = glob.sync(`${firestoreTempDir}/*.api.json`);
    for (const p of paths) {
      const fileName = p.split('/').pop()!;
      fs.copyFileSync(p, `${tmpDir}/${fileName}`);
    }
  } else {
    throw Error(`temp directory not found in packages/firestore`);
  }

  console.log('Generating markdown docs...');
  await spawn(
    'yarn',
    [
      command,
      'markdown',
      '--input',
      'temp',
      '--output',
      outputFolder,
      '--project',
      'js',
      '--sort-functions',
      PREFERRED_PARAMS.join(',')
    ],
    { stdio: 'inherit' }
  );

  console.log('Adding headers to devsite docs...');
  const mdFiles = fs.readdirSync(join(projectRoot, outputFolder));
  for (const mdFile of mdFiles) {
    if (mdFile.endsWith('.md')) {
      const fullPath = join(projectRoot, outputFolder, mdFile);
      const content = fs.readFileSync(fullPath, 'utf-8');
      if (!content.includes('DO NOT EDIT THIS FILE')) {
        fs.writeFileSync(
          fullPath,
          content.replace('\n# ', `\n${GOOGLE3_HEADER}\n# `)
        );
      }
    }
  }
  
  console.log('Done!');
}

run().catch(console.error);
