// Generated by Firebase AI SDK Generator for Web (TypeScript 5.x)
// DO NOT EDIT DIRECTLY - Modify Jinja2 templates instead.

const { describe, it, assert } = await (async () => {
  if (typeof (globalThis as any).describe === 'function' && typeof (globalThis as any).it === 'function') {
    const vitestModule = (globalThis as any).assert ? globalThis : await import('vitest');
    return { describe: (globalThis as any).describe, it: (globalThis as any).it, assert: (vitestModule as any).assert };
  }
  const nodeTest = await import('node:test');
  const nodeAssert = await import('node:assert/strict');
  return { describe: nodeTest.describe, it: nodeTest.it, assert: nodeAssert.default || nodeAssert };
})();
import { BackendResolver } from '../../src/transport/backendResolver.js';

describe('BackendResolver', () => {
  it('resolves Google AI direct unary endpoint and headers', () => {
    const resolver = new BackendResolver({
      config: { target: 'googleAI' },
      apiKey: 'test-api-key',
      clientVersion: 'fire-ai-web/1.0.0',
    });

    const endpoint = resolver.resolveEndpoint(false);
    assert.equal(
      endpoint,
      'https://generativelanguage.googleapis.com/v1beta/interactions'
    );

    const headers = resolver.resolveHeaders(false);
    assert.equal(headers['Content-Type'], 'application/json; charset=utf-8');
    assert.equal(headers['x-goog-api-key'], 'test-api-key');
    assert.equal(headers['X-Firebase-Client'], 'fire-ai-web/1.0.0');
    assert.ok(headers['X-Goog-Api-Client'].includes('gl-js/'));
    assert.equal(headers['Accept'], undefined);
  });

  it('resolves Google AI streaming endpoint and headers', () => {
    const resolver = new BackendResolver({
      config: { target: 'googleAI' },
      apiKey: 'test-api-key',
    });

    const endpoint = resolver.resolveEndpoint(true);
    assert.equal(
      endpoint,
      'https://generativelanguage.googleapis.com/v1beta/interactions?alt=sse'
    );

    const headers = resolver.resolveHeaders(true);
    assert.equal(headers['Accept'], 'text/event-stream');
    assert.equal(headers['Cache-Control'], 'no-cache');
  });

  it('resolves Agent Platform global endpoint with Bearer auth', () => {
    const resolver = new BackendResolver({
      config: {
        target: { agentPlatform: { location: 'global' } },
        projectId: 'my-project-123',
      },
      apiKey: '',
      authToken: 'sample-bearer-token',
    });

    const endpoint = resolver.resolveEndpoint(false);
    assert.equal(
      endpoint,
      'https://aiplatform.googleapis.com/v1beta/projects/my-project-123/locations/global/interactions'
    );

    const headers = resolver.resolveHeaders(false);
    assert.equal(headers['Authorization'], 'Bearer sample-bearer-token');
    assert.equal(headers['x-goog-api-key'], undefined);
  });

  it('honors customBaseUrl overrides', () => {
    const resolver = new BackendResolver({
      config: { customBaseUrl: 'https://mock.localhost:8080' },
      apiKey: 'custom-key',
    });

    const endpoint = resolver.resolveEndpoint(false);
    assert.equal(endpoint, 'https://mock.localhost:8080/v1beta/interactions');
  });
});