// Generated by Firebase AI SDK Generator for Web (TypeScript 5.x)
// DO NOT EDIT DIRECTLY - Modify Jinja2 templates instead.

const { describe, it, assert } = await (async () => {
  if (typeof (globalThis as any).describe === 'function' && typeof (globalThis as any).it === 'function') {
    const vitestModule = (globalThis as any).assert ? globalThis : await import('vitest');
    return { describe: (globalThis as any).describe, it: (globalThis as any).it, assert: (vitestModule as any).assert };
  }
  const nodeTest = await import('node:test');
  const nodeAssert = await import('node:assert/strict');
  return { describe: nodeTest.describe, it: nodeTest.it, assert: nodeAssert.default || nodeAssert };
})();
import { decodeSSEStream } from '../../src/transport/sseEventDecoder.js';

describe('SSEEventDecoder', () => {
  it('decodes single data event chunk', async () => {
    const text = 'data: {"interaction":{"id":"int_123","status":"IN_PROGRESS"}}\n\n';
    const stream = new ReadableStream<Uint8Array>({
      start(controller) {
        controller.enqueue(new TextEncoder().encode(text));
        controller.close();
      },
    });

    const events = [];
    for await (const event of decodeSSEStream(stream)) {
      events.push(event);
    }

    assert.equal(events.length, 1);
    assert.equal(events[0].interaction?.id, 'int_123');
    assert.equal(events[0].interaction?.status, 'IN_PROGRESS');
  });

  it('terminates iteration upon receiving [DONE] sentinel', async () => {
    const text =
      'data: {"step":{"id":"step_1"}}\n\n' +
      'data: [DONE]\n\n' +
      'data: {"step":{"id":"should_not_reach"}}\n\n';

    const stream = new ReadableStream<Uint8Array>({
      start(controller) {
        controller.enqueue(new TextEncoder().encode(text));
        controller.close();
      },
    });

    const events = [];
    for await (const event of decodeSSEStream(stream)) {
      events.push(event);
    }

    assert.equal(events.length, 2);
    assert.equal(events[0].step?.id, 'step_1');
    assert.equal(events[1].isDone, true);
    assert.equal(events[1].eventType, 'done');
  });
});