/* eslint-disable no-console */
/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generates and verifies the pipelines_extra_lib.txt file for the Firestore Query Editor.
 * 
 * 1. Reads the pruned pipelines.d.ts.
 * 2. Uses regex to strip module syntax (import/export).
 * 3. Appends required hardcoded UI types.
 * 4. Runs an in-memory TypeScript compilation to verify the generated code is valid.
 * 5. Writes the result to the output file.
 */

import * as fs from 'fs';
import * as path from 'path';

import * as ts from 'typescript';

// Parse arguments
const args: string[] = process.argv.slice(2);
let sourceDtsPath: string = '';
let destTxtPath: string = '';

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--input' && args[i + 1]) {
    sourceDtsPath = path.resolve(process.cwd(), args[i + 1]);
    i++;
  } else if (args[i] === '--output' && args[i + 1]) {
    destTxtPath = path.resolve(process.cwd(), args[i + 1]);
    i++;
  }
}

if (!sourceDtsPath || !destTxtPath) {
  console.error('❌ Error: Missing required arguments.');
  console.error(
    'Usage: ts-node build-console-ui-types.ts --input <path/to/pipelines.d.ts> --output <path/to/output.txt>'
  );
  process.exit(1);
}

if (!fs.existsSync(sourceDtsPath)) {
  console.error(`❌ Error: Source file not found: ${sourceDtsPath}`);
  process.exit(1);
}

// Hard-coded UI types
const HEADER: string = `// AUTO-GENERATED BY https://github.com/firebase/firebase-js-sdk/blob/main/packages/firestore/scripts/build-console-ui-types.ts
// DO NOT EDIT MANUALLY
//
//
// Purpose:
// This file provides TypeScript declarations (.d.ts) for the Firestore Pipelines
// API, tailored for use within the Firebase Console's Firestore UI code in Google3.
// It enables type checking, autocompletion, and a clear API contract for the UI
// components interacting with Firestore Pipelines.
//
// Structure:
// 1. Manual Definitions: The initial section of this file contains hand-crafted
//    type definitions. These include:
//    - A base \`Firestore\` interface exposing the \`pipeline()\` method.
//    - Common Firestore data types (e.g., Timestamp, GeoPoint, VectorValue).
//    - Stubs for types like \`Query\` and \`DocumentReference\` set to \`never\`
//      to discourage their use in this context.
//
// 2. Auto-populated Pipelines Types: The section below the marker
//    "// BEGIN PIPELINE TYPES" is automatically populated from the
//    Firebase JavaScript SDK build.

interface Firestore {
    pipeline(): PipelineSource<Pipeline>;
}

/**
 * @type {Firestore}
*/
declare var db: Firestore;

/**
 * Not supported in the query editor.
 */
type Query = never;

/**
 * Not supported in the query editor.
 */
type DocumentReference = never;

/**
 * A \`FieldPath\` refers to a field in a document. The path may consist of a
 * single field name (referring to a top-level field in the document), or a
 * list of field names (referring to a nested field in the document).
 *
 * Create a \`FieldPath\` by providing field names. If more than one field
 * name is provided, the path will point to a nested field in a document.
 */
declare class FieldPath {
    /**
     * Creates a \`FieldPath\` from the provided field names. If more than one field
     * name is provided, the path will point to a nested field in a document.
     *
     * @param fieldNames - A list of field names.
     */
    constructor(...fieldNames: string[]);
    /**
     * Returns true if this \`FieldPath\` is equal to the provided one.
     *
     * @param other - The \`FieldPath\` to compare against.
     * @returns true if this \`FieldPath\` is equal to the provided one.
     */
    isEqual(other: FieldPath): boolean;
}

/**
 * Creates a new \`VectorValue\` constructed with a copy of the given array of numbers.
 *
 * @param values - Create a \`VectorValue\` instance with a copy of this array of numbers.
 *
 * @returns A new \`VectorValue\` constructed with a copy of the given array of numbers.
 */
declare function vector(values?: number[]): VectorValue;

/**
 * Represents a vector type in Firestore documents.
 * Create an instance with <code>{@link vector}</code>.
 *
 * @class VectorValue
 */
declare class VectorValue {
    /**
     * Returns a copy of the raw number array form of the vector.
     */
    toArray(): number[];
    /**
     * Returns \`true\` if the two \`VectorValue\` values have the same raw number arrays, returns \`false\` otherwise.
     */
    isEqual(other: VectorValue): boolean;
    /**
     * Returns a JSON-serializable representation of this \`VectorValue\` instance.
     *
     * @returns a JSON representation of this object.
     */
    toJSON(): object;
    /**
     * Builds a \`VectorValue\` instance from a JSON object created by {@link VectorValue.toJSON}.
     *
     * @param json a JSON object represention of a \`VectorValue\` instance.
     * @returns an instance of {@link VectorValue} if the JSON object could be parsed. Throws a
     * {@link FirestoreError} if an error occurs.
     */
    static fromJSON(json: object): VectorValue;
}

/**
 * An immutable object representing an array of bytes.
 */
declare class Bytes {
    private constructor();
    /**
     * Creates a new \`Bytes\` object from the given Base64 string, converting it to
     * bytes.
     *
     * @param base64 - The Base64 string used to create the \`Bytes\` object.
     */
    static fromBase64String(base64: string): Bytes;
    /**
     * Creates a new \`Bytes\` object from the given Uint8Array.
     *
     * @param array - The Uint8Array used to create the \`Bytes\` object.
     */
    static fromUint8Array(array: Uint8Array): Bytes;
    /**
     * Returns the underlying bytes as a Base64-encoded string.
     *
     * @returns The Base64-encoded string created from the \`Bytes\` object.
     */
    toBase64(): string;
    /**
     * Returns the underlying bytes in a new \`Uint8Array\`.
     *
     * @returns The Uint8Array created from the \`Bytes\` object.
     */
    toUint8Array(): Uint8Array;
    /**
     * Returns a string representation of the \`Bytes\` object.
     *
     * @returns A string representation of the \`Bytes\` object.
     */
    toString(): string;
    /**
     * Returns true if this \`Bytes\` object is equal to the provided one.
     *
     * @param other - The \`Bytes\` object to compare against.
     * @returns true if this \`Bytes\` object is equal to the provided one.
     */
    isEqual(other: Bytes): boolean;
    /**
     * Returns a JSON-serializable representation of this \`Bytes\` instance.
     *
     * @returns a JSON representation of this object.
     */
    toJSON(): object;
    /**
     * Builds a \`Bytes\` instance from a JSON object created by {@link Bytes.toJSON}.
     *
     * @param json a JSON object represention of a \`Bytes\` instance
     * @returns an instance of {@link Bytes} if the JSON object could be parsed. Throws a
     * {@link FirestoreError} if an error occurs.
     */
    static fromJSON(json: object): Bytes;
}

/**
 * A \`Timestamp\` represents a point in time independent of any time zone or
 * calendar, represented as seconds and fractions of seconds at nanosecond
 * resolution in UTC Epoch time.
 *
 * It is encoded using the Proleptic Gregorian Calendar which extends the
 * Gregorian calendar backwards to year one. It is encoded assuming all minutes
 * are 60 seconds long, i.e. leap seconds are "smeared" so that no leap second
 * table is needed for interpretation. Range is from 0001-01-01T00:00:00Z to
 * 9999-12-31T23:59:59.999999999Z.
 *
 * For examples and further specifications, refer to the
 * {@link https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto | Timestamp definition}.
 */
declare class Timestamp {
    /**
     * The number of seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z.
     */
    readonly seconds: number;
    /**
     * The fractions of a second at nanosecond resolution.*
     */
    readonly nanoseconds: number;
    /**
     * Creates a new timestamp with the current date, with millisecond precision.
     *
     * @returns a new timestamp representing the current date.
     */
    static now(): Timestamp;
    /**
     * Creates a new timestamp from the given date.
     *
     * @param date - The date to initialize the \`Timestamp\` from.
     * @returns A new \`Timestamp\` representing the same point in time as the given
     *     date.
     */
    static fromDate(date: Date): Timestamp;
    /**
     * Creates a new timestamp from the given number of milliseconds.
     *
     * @param milliseconds - Number of milliseconds since Unix epoch
     *     1970-01-01T00:00:00Z.
     * @returns A new \`Timestamp\` representing the same point in time as the given
     *     number of milliseconds.
     */
    static fromMillis(milliseconds: number): Timestamp;
    /**
     * Creates a new timestamp.
     *
     * @param seconds - The number of seconds of UTC time since Unix epoch
     *     1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
     *     9999-12-31T23:59:59Z inclusive.
     * @param nanoseconds - The non-negative fractions of a second at nanosecond
     *     resolution. Negative second values with fractions must still have
     *     non-negative nanoseconds values that count forward in time. Must be
     *     from 0 to 999,999,999 inclusive.
     */
    constructor(
    /**
     * The number of seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z.
     */
    seconds: number, 
    /**
     * The fractions of a second at nanosecond resolution.*
     */
    nanoseconds: number);
    /**
     * Converts a \`Timestamp\` to a JavaScript \`Date\` object. This conversion
     * causes a loss of precision since \`Date\` objects only support millisecond
     * precision.
     *
     * @returns JavaScript \`Date\` object representing the same point in time as
     *     this \`Timestamp\`, with millisecond precision.
     */
    toDate(): Date;
    /**
     * Converts a \`Timestamp\` to a numeric timestamp (in milliseconds since
     * epoch). This operation causes a loss of precision.
     *
     * @returns The point in time corresponding to this timestamp, represented as
     *     the number of milliseconds since Unix epoch 1970-01-01T00:00:00Z.
     */
    toMillis(): number;
    /**
     * Returns true if this \`Timestamp\` is equal to the provided one.
     *
     * @param other - The \`Timestamp\` to compare against.
     * @returns true if this \`Timestamp\` is equal to the provided one.
     */
    isEqual(other: Timestamp): boolean;
    /** Returns a textual representation of this \`Timestamp\`. */
    toString(): string;
    /**
     * Returns a JSON-serializable representation of this \`Timestamp\`.
     */
    toJSON(): {
        seconds: number;
        nanoseconds: number;
        type: string;
    };
    /**
     * Builds a \`Timestamp\` instance from a JSON object created by {@link Timestamp.toJSON}.
     */
    static fromJSON(json: object): Timestamp;
    /**
     * Converts this object to a primitive string, which allows \`Timestamp\` objects
     * to be compared using the \`>\`, \`<=\`, \`>=\` and \`>\` operators.
     */
    valueOf(): string;
}

/**
 * An immutable object representing a geographic location in Firestore. The
 * location is represented as latitude/longitude pair.
 *
 * Latitude values are in the range of [-90, 90].
 * Longitude values are in the range of [-180, 180].
 */
declare class GeoPoint {
    /**
     * Creates a new immutable \`GeoPoint\` object with the provided latitude and
     * longitude values.
     * @param latitude - The latitude as number between -90 and 90.
     * @param longitude - The longitude as number between -180 and 180.
     */
    constructor(latitude: number, longitude: number);
    /**
     * The latitude of this \`GeoPoint\` instance.
     */
    get latitude(): number;
    /**
     * The longitude of this \`GeoPoint\` instance.
     */
    get longitude(): number;
    /**
     * Returns true if this \`GeoPoint\` is equal to the provided one.
     *
     * @param other - The \`GeoPoint\` to compare against.
     * @returns true if this \`GeoPoint\` is equal to the provided one.
     */
    isEqual(other: GeoPoint): boolean;
    /**
     * Returns a JSON-serializable representation of this \`GeoPoint\` instance.
     *
     * @returns a JSON representation of this object.
     */
    toJSON(): {
        latitude: number;
        longitude: number;
        type: string;
    };
    /**
     * Builds a \`GeoPoint\` instance from a JSON object created by {@link GeoPoint.toJSON}.
     *
     * @param json a JSON object represention of a \`GeoPoint\` instance
     * @returns an instance of {@link GeoPoint} if the JSON object could be parsed. Throws a
     * {@link FirestoreError} if an error occurs.
     */
    static fromJSON(json: object): GeoPoint;
}

type DocumentData = { [field: string]: any };

// ============================================================================
// BEGIN PIPELINE TYPES (Pruned from source)
// ============================================================================
`;
// Regex processing to remove ES module syntax (import/export statements)
let dtsContent: string = fs.readFileSync(sourceDtsPath, 'utf8');

// Strip multi-line and single-line imports
dtsContent = dtsContent.replace(/^import\s+[\s\S]*?from\s+['"][^'"]+['"];?\s*$/gm, '');
dtsContent = dtsContent.replace(/^import\s+['"][^'"]+['"];?\s*$/gm, '');

// Strip bulk exports: export { Foo, Bar };
dtsContent = dtsContent.replace(/^export\s+\{[\s\S]*?\};?\s*$/gm, '');

// Strip 'export ' modifiers from the beginning of lines.
// This converts 'export declare class' -> 'declare class', which is standard
// for ambient global declaration files.
dtsContent = dtsContent.replace(/^\s*export\s+/gm, '');

const finalContent: string = HEADER + '\n' + dtsContent;

// Verify the final content is valid TypeScript
const outputDir: string = path.dirname(destTxtPath);
const tempDtsPath: string = path.join(outputDir, 'temp_ui_types.d.ts');
const tempTestPath: string = path.join(outputDir, 'temp_ui_test.ts');

fs.writeFileSync(tempDtsPath, finalContent);
fs.writeFileSync(
  tempTestPath,
  `
  /// <reference path="./temp_ui_types.d.ts" />
  
  // Test 1: Verify the UI 'db' entry point and pipeline chaining works
  const p = db.pipeline()
    .collection("books")
    .where(equal("title", "1984"))
    .select("author");

  // Test 2: Verify hardcoded types exist and align with pipeline expectations
  const ts: Timestamp = Timestamp.now();
  const pt: GeoPoint = new GeoPoint(1, 2);
  const vec: VectorValue = vector([1.0, 2.0]);
  const b: Bytes = Bytes.fromBase64String("abc");
  const path: FieldPath = new FieldPath("field");
`
);

// Run the TS Compiler
const program: ts.Program = ts.createProgram([tempTestPath], {
  noEmit: true,
  strict: true,
  skipLibCheck: true // Skip internal .d.ts formatting quirks, just verify the API contract works.
});

const diagnostics: readonly ts.Diagnostic[] = ts.getPreEmitDiagnostics(program);

// Cleanup temp files immediately
try {
  fs.unlinkSync(tempDtsPath);
  fs.unlinkSync(tempTestPath);
} catch (e) {
  // Ignore errors if temp files couldn't be deleted
}

if (diagnostics.length > 0) {
  console.error('ERROR: Type verification failed for Console UI pipeline types!');
  console.error(
    'This usually means the hardcoded types in build-console-ui-types.ts drifted from the SDK, or the regex stripped too much.'
  );

  diagnostics.forEach((diag) => {
    if (diag.file) {
      const { line, character } = ts.getLineAndCharacterOfPosition(diag.file, diag.start!);
      const message = ts.flattenDiagnosticMessageText(diag.messageText, '\n');
      console.error(`${diag.file.fileName} (${line + 1},${character + 1}): ${message}`);
    } else {
      console.error(ts.flattenDiagnosticMessageText(diag.messageText, '\n'));
    }
  });

  process.exit(1); // Fail the build
}

// Write output
fs.writeFileSync(destTxtPath, finalContent);
console.log(`✅ Successfully generated and verified console UI types at ${destTxtPath}`);
