name: 🐞 Bug Report V2
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    id: before-you-start
    attributes:
      value: |
        *[READ THIS]:* to evaluate if you are in the right place?
        - For issues or feature requests related to __the code in this repository__, file a Github issue.
        - If this is a __feature request__, make sure the issue title starts with "FR:".
        - For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) with the firebase tag.
        - For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk) google group.
        - For help troubleshooting your application that does not fall under one of the above categories, reach out to the personalized [Firebase support channel](https://firebase.google.com/support/).
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: Describe your operating system
      placeholder: ex. iOS 16.4
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: Describe your browser version
      placeholder: ex. Safari/604.1
    validations:
      required: true
  - type: input
    id: firebase-sdk-version
    attributes:
      label: Firebase SDK Version
      description: Describe your Firebase SDK Version
      placeholder: ex. 9.16.0
    validations:
      required: true
  - type: dropdown
    id: firebase-sdk-products
    attributes:
      label: Firebase SDK Products
      description: What Firebase SDK Products is your app using?
      multiple: true
      options:
        - Analytics
        - App-Check
        - Auth
        - Component
        - Database
        - Firestore
        - Functions
        - Installations
        - Logger
        - Messaging
        - Performance
        - Remote-Config
        - Storage
    validations:
      required: true
  - type: textarea
    id: project-tooling
    attributes:
      label: Describe your project's tooling
      description: Describe the tooling your app is built with
      placeholder: React app with Webpack and Jest
    validations:
      required: true
  - type: textarea
    id: describe-your-problem
    attributes:
      label: Describe the problem
      description: Describe what you were trying to do and what occurred
      placeholder: |
        'What were you trying to accomplish? What happened?'
        'This should include a background description, log/console output, etc.'
    validations:
      required: true
  - type: textarea
    id: reproduce-code
    attributes:
      label: Code to reproduce issue
      description: Please copy and paste any relevant code here to reproduce the problem or links to code to reproduce it. This will be automatically formatted into code, so no need for backticks.
      render: javascript
    validations:
      required: true
