blank_issues_enabled: false
contact_links:
  - name: 🔥 Firebase Support
    url: https://firebase.google.com/support/
    about: If you have an urgent issue with your app in production, please contact support.
