// Generated by Firebase AI SDK Generator for Web (TypeScript 5.x)
// DO NOT EDIT DIRECTLY - Modify Jinja2 templates instead.

const { describe, it, assert } = await (async () => {
  if (typeof (globalThis as any).describe === 'function' && typeof (globalThis as any).it === 'function') {
    const vitestModule = (globalThis as any).assert ? globalThis : await import('vitest');
    return { describe: (globalThis as any).describe, it: (globalThis as any).it, assert: (vitestModule as any).assert };
  }
  const nodeTest = await import('node:test');
  const nodeAssert = await import('node:assert/strict');
  return { describe: nodeTest.describe, it: nodeTest.it, assert: nodeAssert.default || nodeAssert };
})();
import { InteractionSession } from '../../src/client/interactionSession.js';

describe('InteractionSession', () => {
  it('initializes with model and optional config', () => {
    const mockClient = {} as any;
    const session = new InteractionSession(mockClient, { model: 'gemini-2.5-flash' });

    assert.equal(session.model, 'gemini-2.5-flash');
    assert.equal(session.currentInteractionId, undefined);
    assert.equal(session.history.length, 0);
  });

  it('updates currentInteractionId and history after interaction completes', async () => {
    const mockClient = {
      create: async (params: any) => {
        assert.equal(params.model, 'gemini-2.5-flash');
        return {
          id: 'int_chain_001',
          status: 'COMPLETED',
          model: 'gemini-2.5-flash',
        };
      },
    } as any;

    const session = new InteractionSession(mockClient, { model: 'gemini-2.5-flash' });
    const result = await session.sendMessage('Turn 1 prompt');

    assert.equal(result.id, 'int_chain_001');
    assert.equal(session.currentInteractionId, 'int_chain_001');
    assert.equal(session.history.length, 1);
  });

  it('auto-chains previousInteractionId on subsequent turns', async () => {
    let capturedPreviousId: string | undefined;
    const mockClient = {
      create: async (params: any) => {
        capturedPreviousId = params.previousInteractionId;
        return {
          id: 'int_chain_002',
          status: 'COMPLETED',
          model: 'gemini-2.5-flash',
        };
      },
    } as any;

    const session = new InteractionSession(mockClient, {
      model: 'gemini-2.5-flash',
      initialInteractionId: 'int_chain_001',
    });

    await session.sendMessage('Turn 2 prompt');
    assert.equal(capturedPreviousId, 'int_chain_001');
    assert.equal(session.currentInteractionId, 'int_chain_002');
  });
});