// Generated by Firebase AI SDK Generator for Web (TypeScript 5.x)
// DO NOT EDIT DIRECTLY - Modify Jinja2 templates instead.

import { BackendResolver } from '../transport/backendResolver';
import {
  decodeSSEStream,
  InteractionsError,
  parseInteractionsError,
  type InteractionStreamingEvent,
  type InteractionErrorCategory,
  type InteractionErrorCode,
} from '../transport/sseEventDecoder';
import type { AgentConfig } from '../types/internal/agents';
import type { Interaction, SafetySetting, ResponseFormat } from '../types/internal/interaction';
import type { Tool, GenerationConfig } from '../types/internal/tools';
import { InteractionSession } from './interactionSession';

export { InteractionsError, type InteractionErrorCategory, type InteractionErrorCode };

export interface CreateInteractionOptions {
  model?: string;
  agent?: string;
  agentConfig?: AgentConfig;
  input: string | Record<string, unknown> | Array<unknown>;
  tools?: Tool[];
  generationConfig?: GenerationConfig;
  systemInstruction?: string;
  safetySettings?: SafetySetting[];
  responseFormat?: ResponseFormat;
  previousInteractionId?: string;
  additionalParams?: Record<string, unknown>;
}

export interface StreamResult {
  stream: AsyncIterable<InteractionStreamingEvent>;
  response: Promise<Interaction>;
}

export class InteractionsClient {
  constructor(private readonly resolver: BackendResolver) {}

  async create(options: CreateInteractionOptions): Promise<Interaction> {
    const url = this.resolver.resolveEndpoint(false);
    const headers = this.resolver.resolveHeaders(false);
    const payload = this.buildPayload(options);

    const res = await fetch(url, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const err = await res.text();
      throw parseInteractionsError(res.status, err);
    }

    return (await res.json()) as Interaction;
  }

  async createStream(options: CreateInteractionOptions): Promise<StreamResult> {
    const url = this.resolver.resolveEndpoint(true);
    const headers = this.resolver.resolveHeaders(true);
    const payload = this.buildPayload(options);
    payload.stream = true;

    const res = await fetch(url, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
    });

    if (!res.ok || !res.body) {
      const err = await res.text();
      throw parseInteractionsError(res.status, err);
    }

    let finalInteraction: Interaction | undefined;
    let resolveInteraction: (val: Interaction) => void;
    let rejectInteraction: (err: unknown) => void;

    const responsePromise = new Promise<Interaction>((resolve, reject) => {
      resolveInteraction = resolve;
      rejectInteraction = reject;
    });

    const generator = decodeSSEStream(res.body);

    const stream = (async function* () {
      try {
        for await (const event of generator) {
          if (event.interaction) {
            finalInteraction = event.interaction;
          }
          yield event;
        }
        if (finalInteraction) {
          resolveInteraction(finalInteraction);
        } else {
          rejectInteraction(new Error('Stream ended without final interaction payload.'));
        }
      } catch (err) {
        rejectInteraction(err);
        throw err;
      }
    })();

    return {
      stream,
      response: responsePromise,
    };
  }

  async get(interactionId: string): Promise<Interaction> {
    const base = this.resolver.resolveEndpoint(false);
    const url = `${base}/${interactionId}`;
    const headers = this.resolver.resolveHeaders(false);

    const res = await fetch(url, { method: 'GET', headers });
    if (!res.ok) throw parseInteractionsError(res.status, await res.text());
    return (await res.json()) as Interaction;
  }

  async cancel(interactionId: string): Promise<Interaction> {
    const base = this.resolver.resolveEndpoint(false);
    const url = `${base}/${interactionId}:cancel`;
    const headers = this.resolver.resolveHeaders(false);

    const res = await fetch(url, { method: 'POST', headers });
    if (!res.ok) throw parseInteractionsError(res.status, await res.text());
    return (await res.json()) as Interaction;
  }

  async delete(interactionId: string): Promise<void> {
    const base = this.resolver.resolveEndpoint(false);
    const url = `${base}/${interactionId}`;
    const headers = this.resolver.resolveHeaders(false);

    const res = await fetch(url, { method: 'DELETE', headers });
    if (!res.ok) throw parseInteractionsError(res.status, await res.text());
  }

  startSession(options?: {
    model?: string;
    agent?: string;
    tools?: Tool[];
    generationConfig?: GenerationConfig;
    systemInstruction?: string;
    safetySettings?: SafetySetting[];
    responseFormat?: ResponseFormat;
    localToolHandlers?: Record<string, (args: Record<string, unknown>) => Promise<Record<string, unknown>>>;
  }): InteractionSession {
    return new InteractionSession(this, options);
  }

  private buildPayload(options: CreateInteractionOptions): Record<string, unknown> {
    const payload: Record<string, unknown> = {
      input: options.input,
    };
    if (options.model) payload.model = options.model;
    if (options.agent) payload.agent = options.agent;
    if (options.agentConfig) payload.agent_config = options.agentConfig;
    if (options.tools && options.tools.length > 0) payload.tools = options.tools;
    if (options.systemInstruction) payload.system_instruction = options.systemInstruction;
    if (options.safetySettings && options.safetySettings.length > 0) payload.safety_settings = options.safetySettings;
    if (options.responseFormat) payload.response_format = options.responseFormat;
    if (options.generationConfig) payload.generation_config = serializeGenerationConfig(options.generationConfig);
    if (options.previousInteractionId) payload.previous_interaction_id = options.previousInteractionId;
    if (options.additionalParams) Object.assign(payload, options.additionalParams);
    return payload;
  }
}

function serializeGenerationConfig(config: GenerationConfig | Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(config)) {
    if (value === undefined) continue;
    switch (key) {
      case 'maxOutputTokens':
        result['max_output_tokens'] = value;
        break;
      case 'stopSequences':
        result['stop_sequences'] = value;
        break;
      case 'thinkingLevel':
        result['thinking_level'] = value;
        break;
      case 'thinkingSummaries':
        result['thinking_summaries'] = value;
        break;
      case 'speechConfig':
        result['speech_config'] = value;
        break;
      case 'toolChoice':
        result['tool_choice'] = value;
        break;
      case 'transcriptionConfig':
        result['transcription_config'] = value;
        break;
      case 'videoConfig':
        result['video_config'] = value;
        break;
      default:
        result[key] = value;
        break;
    }
  }
  return result;
}