// Generated by Firebase AI SDK Generator for Web (TypeScript 5.x)
// DO NOT EDIT DIRECTLY - Modify Jinja2 templates instead.

import { InteractionsClient, type StreamResult } from './interactionsClient';
import type { Interaction, SafetySetting, ResponseFormat } from '../types/internal/interaction';
import type { Tool, GenerationConfig } from '../types/internal/tools';

export type LocalToolHandler = (args: Record<string, unknown>) => Promise<Record<string, unknown>>;

export class InteractionSession {
  readonly model?: string;
  readonly agent?: string;
  readonly tools?: Tool[];
  readonly generationConfig?: GenerationConfig;
  readonly systemInstruction?: string;
  readonly safetySettings?: SafetySetting[];
  readonly responseFormat?: ResponseFormat;
  private readonly toolHandlers: Map<string, LocalToolHandler>;
  private _currentInteractionId?: string;
  private readonly _history: Interaction[] = [];

  constructor(
    private readonly client: InteractionsClient,
    options?: {
      model?: string;
      agent?: string;
      tools?: Tool[];
      generationConfig?: GenerationConfig;
      systemInstruction?: string;
      safetySettings?: SafetySetting[];
      responseFormat?: ResponseFormat;
      localToolHandlers?: Record<string, LocalToolHandler>;
      initialInteractionId?: string;
    }
  ) {
    this.model = options?.model;
    this.agent = options?.agent;
    this.tools = options?.tools;
    this.generationConfig = options?.generationConfig;
    this.systemInstruction = options?.systemInstruction;
    this.safetySettings = options?.safetySettings;
    this.responseFormat = options?.responseFormat;
    this.toolHandlers = new Map(Object.entries(options?.localToolHandlers ?? {}));
    this._currentInteractionId = options?.initialInteractionId;
  }

  get currentInteractionId(): string | undefined {
    return this._currentInteractionId;
  }

  get history(): ReadonlyArray<Interaction> {
    return this._history;
  }

  registerTool(name: string, handler: LocalToolHandler): void {
    this.toolHandlers.set(name, handler);
  }

  async sendMessage(input: string | Record<string, unknown> | Array<unknown>, maxToolTurns = 5): Promise<Interaction> {
    let turns = 0;
    let currentInput: string | Record<string, unknown> | Array<unknown> = input;

    while (turns < maxToolTurns) {
      turns++;

      const interaction = await this.client.create({
        model: this.model,
        agent: this.agent,
        input: currentInput,
        tools: this.tools,
        generationConfig: this.generationConfig,
        systemInstruction: this.systemInstruction,
        safetySettings: this.safetySettings,
        responseFormat: this.responseFormat,
        previousInteractionId: this._currentInteractionId,
      });

      this._currentInteractionId = interaction.id;
      this._history.push(interaction);

      // Check for function call
      const funcStep = (interaction.steps as any[])?.find((s: any) => s.type === 'function_call');
      if (funcStep) {
        const toolName = (funcStep.name || funcStep.function_name || '') as string;
        const handler = this.toolHandlers.get(toolName);
        if (handler) {
          const args = (funcStep.args || funcStep.arguments || {}) as Record<string, unknown>;
          const toolResult = await handler(args);
          const callId = (funcStep.call_id || funcStep.id || '') as string;
          currentInput = [
            {
              type: 'function_result',
              name: toolName,
              call_id: callId,
              result: JSON.stringify(toolResult),
            },
          ];
          continue;
        }
      }

      return interaction;
    }

    throw new Error(`Exceeded maximum autonomous tool turns (${maxToolTurns}).`);
  }

  async sendMessageStream(input: string): Promise<StreamResult> {
    const res = await this.client.createStream({
      model: this.model,
      agent: this.agent,
      input,
      tools: this.tools,
      generationConfig: this.generationConfig,
      systemInstruction: this.systemInstruction,
      safetySettings: this.safetySettings,
      responseFormat: this.responseFormat,
      previousInteractionId: this._currentInteractionId,
    });

    const self = this;
    const originalStream = res.stream;

    const wrappedStream = (async function* () {
      for await (const chunk of originalStream) {
        if (chunk.interaction?.id) {
          self._currentInteractionId = chunk.interaction.id;
        }
        yield chunk;
      }
    })();

    return {
      stream: wrappedStream,
      response: res.response.then((interaction) => {
        self._currentInteractionId = interaction.id;
        self._history.push(interaction);
        return interaction;
      }),
    };
  }
}