/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// eslint-disable-next-line import/no-extraneous-dependencies
import {
  createUserWithEmailAndPassword,
  EmailAuthProvider,
  reload,
  signInWithCredential,
  signInWithEmailAndPassword,
  updateProfile,
  Auth,
  OperationType,
  UserCredential,
  getAdditionalUserInfo
} from '@firebase/auth';
import { FirebaseError } from '@firebase/util';

import {
  cleanUpTestInstance,
  getTestInstance,
  randomEmail
} from '../../helpers/integration/helpers';
import { generateMiddlewareTests } from './middleware_test_generator';
describe('Integration test: email/password auth', () => {
  let auth: Auth;
  let email: string;
  let password: string;

  beforeEach(() => {
    auth = getTestInstance();
    email = randomEmail();
    password = 'password';
    // Uncomment the following line if you want an autogenerated password that complies with password policy in the test project.
    // password = await generateValidPassword(auth);
  });

  afterEach(() => cleanUpTestInstance(auth));

  it('allows user to sign up', async () => {
    const userCred = await createUserWithEmailAndPassword(
      auth,
      email,
      password
    );
    expect(auth.currentUser).toBe(userCred.user);
    expect(userCred.operationType).toBe(OperationType.SIGN_IN);

    const user = userCred.user;
    expect(user.isAnonymous).toBe(false);
    expect(user.uid).to.be.a('string');
    expect(user.email).toBe(email);
    expect(user.emailVerified).toBe(false);
    expect(user.providerData.length).toBe(1);
    expect(user.providerData[0].providerId).toBe('password');
    expect(user.providerData[0].email).toBe(email);

    const additionalUserInfo = getAdditionalUserInfo(userCred)!;
    expect(additionalUserInfo.isNewUser).toBe(true);
    expect(additionalUserInfo.providerId).toBe('password');
  });

  it('errors when createUser called twice', async () => {
    await createUserWithEmailAndPassword(auth, email, password);
    await expect(
      createUserWithEmailAndPassword(auth, email, password)
    ).rejects.toThrow(FirebaseError, 'auth/email-already-in-use');
  });

  describe('with existing user', () => {
    let signUpCred: UserCredential;

    beforeEach(async () => {
      signUpCred = await createUserWithEmailAndPassword(auth, email, password);
      await auth.signOut();
    });

    it('allows the user to sign in with signInWithEmailAndPassword', async () => {
      const signInCred = await signInWithEmailAndPassword(
        auth,
        email,
        password
      );
      expect(auth.currentUser).toBe(signInCred.user);

      expect(signInCred.operationType).toBe(OperationType.SIGN_IN);
      expect(signInCred.user.uid).toBe(signUpCred.user.uid);
      const additionalUserInfo = getAdditionalUserInfo(signInCred)!;
      expect(additionalUserInfo.isNewUser).toBe(false);
      expect(additionalUserInfo.providerId).toBe('password');
    });

    it('allows the user to sign in with signInWithCredential', async () => {
      const credential = EmailAuthProvider.credential(email, password);
      const signInCred = await signInWithCredential(auth, credential);
      expect(auth.currentUser).toBe(signInCred.user);

      expect(signInCred.operationType).toBe(OperationType.SIGN_IN);
      expect(signInCred.user.uid).toBe(signUpCred.user.uid);
      const additionalUserInfo = getAdditionalUserInfo(signInCred)!;
      expect(additionalUserInfo.isNewUser).toBe(false);
      expect(additionalUserInfo.providerId).toBe('password');
    });

    it('allows the user to update profile', async () => {
      let { user } = await signInWithEmailAndPassword(auth, email, password);
      await updateProfile(user, {
        displayName: 'Display Name',
        photoURL: 'photo-url'
      });
      expect(user.displayName).toBe('Display Name');
      expect(user.photoURL).toBe('photo-url');

      await auth.signOut();

      user = (await signInWithEmailAndPassword(auth, email, password)).user;
      expect(user.displayName).toBe('Display Name');
      expect(user.photoURL).toBe('photo-url');
    });

    it('allows the user to delete the account', async () => {
      const { user } = await signInWithEmailAndPassword(auth, email, password);
      await user.delete();

      await expect(reload(user)).rejects.toThrow(
        FirebaseError,
        'auth/user-token-expired'
      );

      expect(auth.currentUser).toBeNull();
      await expect(
        signInWithEmailAndPassword(auth, email, password)
      ).rejects.toThrow(FirebaseError, 'auth/user-not-found');
    });

    it('sign in can be called twice successively', async () => {
      const { user: userA } = await signInWithEmailAndPassword(
        auth,
        email,
        password
      );
      const { user: userB } = await signInWithEmailAndPassword(
        auth,
        email,
        password
      );
      expect(userA.uid).toBe(userB.uid);
    });

    generateMiddlewareTests(
      () => auth,
      () => {
        return signInWithEmailAndPassword(auth, email, password);
      }
    );
  });
});
