/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// eslint-disable-next-line import/no-extraneous-dependencies
import { Auth, createUserWithEmailAndPassword, User } from '@firebase/auth';
import { randomEmail } from '../../helpers/integration/helpers';

export function generateMiddlewareTests(
  authGetter: () => Auth,
  signIn: () => Promise<unknown>
): void {
  describe('middleware', () => {
    let auth: Auth;
    let unsubscribes: Array<() => void>;
    let password: string;

    beforeEach(() => {
      auth = authGetter();
      unsubscribes = [];
      password = 'password';
      // Uncomment the following line if you want an autogenerated password that complies with password policy in the test project.
      // password = await generateValidPassword(auth);
    });

    afterEach(() => {
      for (const u of unsubscribes) {
        u();
      }
    });

    /**
     * Helper function for adding beforeAuthStateChanged that will
     * automatically unsubscribe after every test (since some tests may
     * perform cleanup after that would be affected by the middleware)
     */
    function beforeAuthStateChanged(
      callback: (user: User | null) => void | Promise<void>,
      onAbort?: () => void
    ): void {
      unsubscribes.push(auth.beforeAuthStateChanged(callback, onAbort));
    }

    it('can prevent user sign in', async () => {
      beforeAuthStateChanged(() => {
        throw new Error('stop sign in');
      });

      await expect(signIn()).rejects.toThrow('auth/login-blocked');
      expect(auth.currentUser).toBeNull();
    });

    it('can prevent user sign in as a promise', async () => {
      beforeAuthStateChanged(() => {
        return Promise.reject('stop sign in');
      });

      await expect(signIn()).rejects.toThrow('auth/login-blocked');
      expect(auth.currentUser).toBeNull();
    });

    it('keeps previously-logged in user if blocked', async () => {
      // Use a random email/password sign in for the base user
      const { user: baseUser } = await createUserWithEmailAndPassword(
        auth,
        randomEmail(),
        password
      );

      beforeAuthStateChanged(() => {
        throw new Error('stop sign in');
      });

      await expect(signIn()).rejects.toThrow('auth/login-blocked');
      expect(auth.currentUser).toBe(baseUser);
    });

    it('can allow sign in', async () => {
      beforeAuthStateChanged(() => {
        // Pass
      });

      await expect(signIn()).resolves.not.toThrow();
      expect(auth.currentUser).not.toBeNull();
    });

    it('can allow sign in as a promise', async () => {
      beforeAuthStateChanged(() => {
        return Promise.resolve();
      });

      await expect(signIn()).resolves.not.toThrow();
      expect(auth.currentUser).not.toBeNull();
    });

    it('overrides previous user if allowed', async () => {
      // Use a random email/password sign in for the base user
      const { user: baseUser } = await createUserWithEmailAndPassword(
        auth,
        randomEmail(),
        password
      );

      beforeAuthStateChanged(() => {
        // Pass
      });

      await expect(signIn()).resolves.not.toThrow();
      expect(auth.currentUser).not.toBe(baseUser);
    });

    it('will reject if one callback fails', async () => {
      // Also check that the function is called multiple
      // times
      const spy = vi.fn();

      beforeAuthStateChanged(spy);
      beforeAuthStateChanged(spy);
      beforeAuthStateChanged(spy);
      beforeAuthStateChanged(() => {
        throw new Error('stop sign in');
      });

      await expect(signIn()).rejects.toThrow('auth/login-blocked');
      expect(auth.currentUser).toBeNull();
      expect(spy).toHaveBeenCalledTimes(3);
    });

    it('keeps previously-logged in user if one rejects', async () => {
      // Use a random email/password sign in for the base user
      const { user: baseUser } = await createUserWithEmailAndPassword(
        auth,
        randomEmail(),
        password
      );

      // Also check that the function is called multiple
      // times
      const spy = vi.fn();

      beforeAuthStateChanged(spy);
      beforeAuthStateChanged(spy);
      beforeAuthStateChanged(spy);
      beforeAuthStateChanged(() => {
        throw new Error('stop sign in');
      });

      await expect(signIn()).rejects.toThrow('auth/login-blocked');
      expect(auth.currentUser).toBe(baseUser);
      expect(spy).toHaveBeenCalledTimes(3);
    });

    it('allows sign in with multiple callbacks all pass', async () => {
      // Use a random email/password sign in for the base user
      const { user: baseUser } = await createUserWithEmailAndPassword(
        auth,
        randomEmail(),
        password
      );

      // Also check that the function is called multiple
      // times
      const spy = vi.fn();

      beforeAuthStateChanged(spy);
      beforeAuthStateChanged(spy);
      beforeAuthStateChanged(spy);

      await expect(signIn()).resolves.not.toThrow();
      expect(auth.currentUser).not.toBe(baseUser);
      expect(spy).toHaveBeenCalledTimes(3);
    });

    it('does not call subsequent callbacks after rejection', async () => {
      const firstSpy = vi.fn();
      const secondSpy = vi.fn();

      beforeAuthStateChanged(firstSpy);
      beforeAuthStateChanged(() => {
        throw new Error('stop sign in');
      });
      beforeAuthStateChanged(secondSpy);

      await expect(signIn()).rejects.toThrow('auth/login-blocked');
      expect(firstSpy).toHaveBeenCalledTimes(1);
      expect(secondSpy).not.toHaveBeenCalled();
    });

    it('can prevent sign-out', async () => {
      await signIn();
      const user = auth.currentUser;

      beforeAuthStateChanged(() => {
        throw new Error('block sign out');
      });

      await expect(auth.signOut()).rejects.toThrow('auth/login-blocked');
      expect(auth.currentUser).toBe(user);
    });

    it('calls onAbort after rejection', async () => {
      const onAbort = vi.fn();
      beforeAuthStateChanged(() => {
        // Pass
      }, onAbort);
      beforeAuthStateChanged(() => {
        throw new Error('block sign out');
      });

      await expect(signIn()).rejects.toThrow('auth/login-blocked');
      expect(onAbort).toHaveBeenCalled();
    });
  });
}
