/**
 * @license
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Base class for types of images that the Imagen Model can return.
 *
 * @internal
 */
export interface ImagenImage {
  mimeType: string;
}

/**
 * Image generated by Imagen to inline bytes.
 *
 * @public
 */
export interface ImagenInlineImage extends ImagenImage {
  bytesBase64Encoded: string;
}

/**
 * Image generated by Imagen, stored in Google Cloud Storage (GCS).
 *
 * @public
 */
export interface ImagenGCSImage extends ImagenImage {
  /**
   * The Google Cloud Storage (GCS) URI at which the generated image is stored.
   */
  gcsURI: string;
}

/**
 * Imagen image response.
 *
 * @public
 */
export interface ImagenInlineImageResponse {
  /**
   * The images generated by Imagen. If all images were filtered, this will be empty.
   */
  images: ImagenInlineImage[];
  /**
   * The reason the missing images were filtered.
   * For the mappings of error codes to reasons, see {@link https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen#safety-categories}.
   */
  filteredReason?: string;
}

export interface ImagenGCSImageResponse {
  images: ImagenGCSImage[];
  filteredReason?: string;
}

export interface ImagenImageReponse {
  images: ImagenImage[];
  filteredReason?: string;
}
