/**
 * @license
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * An image generated by Imagen, represented as inline bytes.
 *
 * @public
 */
export interface ImagenInlineImage {
  /**
   * The MIME type of the image.
   */
  mimeType: string;
  /**
   * The image data encoded as a base64 string.
   */
  bytesBase64Encoded: string;
}

/**
 * An image generated by Imagen, stored in Google Cloud Storage (GCS).
 *
 * @public
 */
export interface ImagenGCSImage {
  /**
   * The MIME type of the image.
   */
  mimeType: string;
  /**
   * The Google Cloud Storage (GCS) URI where the image is stored.
   */
  gcsURI: string;
}

/**
 * The response from a request to generate images to inline bytes.
 *
 * @public
 */
export interface ImagenInlineImageResponse {
  /**
   * The images generated by Imagen.
   * If all images were filtered out due to safety reasons, this array will be empty.
   */
  images: ImagenInlineImage[];
  /**
   * The reason why any images were filtered. This field is only present if one
   * or more images were filtered.
   * For the mappings of error codes to reasons, see
   * {@link https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen#safety-categories}.
   */
  filteredReason?: string;
}

/**
 * The response from a request to generate images to Google Cloud Storage (GCS).
 *
 * @public
 */
export interface ImagenGCSImageResponse {
  /**
   * The images generated by Imagen.
   * If all images were filtered due to safety reasons, this array will be empty.
   */
  images: ImagenGCSImage[];
  /**
   * The reason why any images were filtered. This field is only present if one
   * or more images were filtered.
   * For the mappings of error codes to reasons, see
   * {@link https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen#safety-categories}.
   */
  filteredReason?: string;
}
