/**
 * Defines the image format for images output by Imagen.
 *
 * Use this class to specify the desired format (JPEG or PNG) and compression quality 
 * for images generated by Imagen. This is typically included as part of 
 * {@link ImagenModelParams}.
 *
 * @example
 * ```javascript
 * const imagenModelParams = {
 *   // ... other ImagenModelParams
 *   imageFormat: ImagenImageFormat.jpeg(75) // JPEG with a compression level of 75.
 * }
 * ```
 *
 * @public
 */
export class ImagenImageFormat {
  mimeType: string;
  compressionQuality?: number;

  private constructor() {
    this.mimeType = "image/png";
  }

  /**
   * Creates an ImagenImageFormat for a JPEG image.
   *
   * @param compressionQuality - The level of compression (a number between 0 and 100).
   * @returns ImagenImageFormat
   *
   * @public
   */
  static jpeg(compressionQuality: number): ImagenImageFormat {
    return { mimeType: "image/jpeg", compressionQuality };
  }

  /**
   * Creates an ImageImageFormat for a PNG image.
   *
   * @returns ImageImageFormat
   *
   * @public
   */
  static png(): ImagenImageFormat {
    return { mimeType: "image/png" };
  }
}