# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Doc Change Check (Run "yarn docgen:all" if this fails)

on: pull_request

jobs:
  doc-check:
    name: Check if reference docs have changed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # get all history for the diff
          fetch-depth: 0
      - name: Set up Node (20)
        uses: actions/setup-node@v4
        with:
          node-version: 22.10.0
      - name: Yarn install
        run: yarn
      - name: Run doc generation
        run: yarn docgen:all
      - name: Check for changes in common/api-review dir (fail if so)
        id: api-report-check
        run: |
          if [[ -n "$(git status common/api-review --porcelain)" ]]; then
            echo "Unstaged changes detected in api-report(s):"
            git status -s
            echo "command-to-run='yarn build'" >> $GITHUB_OUTPUT
            exit 1
          fi
        # Overwrite the command if there are also docs-devsite changes since
        # running yarn docgen:all will also run yarn build first.
      - name: Check for changes in docs-devsite dir (fail if so)
        id: docs-check
        run: |
          if [[ -n "$(git status docs-devsite --porcelain)" ]]; then
            echo "Unstaged changes detected in docs-devsite/:"
            git status -s
            echo "command-to-run='yarn docgen:all'" >> $GITHUB_OUTPUT
            exit 1
          fi
      - name: Reference documentation needs to be updated. See message below.
        if: ${{ failure() }}
        run: echo "Changes in this PR affect the reference docs or API reports. Run \`$COMMAND_TO_RUN\` locally to regenerate the changed files and add them to this PR."
        env:
          COMMAND_TO_RUN: ${{ steps.docs-check.outputs.command-to-run || steps.api-report-check.outputs.command-to-run }}
