name: Combine PRs

on:
  workflow_dispatch: # allows you to manually trigger the workflow

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        # This action defaults to combining branches that begin with
        # "dependabot" but can be configured.
        uses: github/combine-prs@v5.2.0
        with:
          labels: combined-pr # Optional: add a label to the combined PR