name: Label doc changes

on: pull_request

env:
  GITHUB_PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  GITHUB_PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}

jobs:
  check_doc_changes:
    name: Check if docs are being changed
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        # This makes Actions fetch all Git history so check_changeset script can diff properly.
        fetch-depth: 0
    - name: Set up Node (14)
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Yarn install
      run: yarn
    - name: Run detect doc changes script
      run: yarn ts-node-script scripts/exp/detect-doc-changes.ts
      id: check-doc-changes
    - name: Print if doc changed output
      run: echo "${{steps.check-doc-changes.outputs.DOC_CHANGED}}"
    - name: Add label if there are doc changes
      uses: actions-ecosystem/action-add-labels@v1.1.0
      if: ${{steps.check-doc-changes.outputs.DOC_CHANGED == 'true'}}
      with:
        labels: doc-changes
        github_token: ${{ secrets.OSS_BOT_GITHUB_TOKEN }}