name: Lint All Packages

on: push

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node (10)
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: yarn install
      run: yarn
    - name: yarn lint
      run: yarn lint
