name: Merge Release Branch To Main

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release (e.g., 12.7.0)'
        required: true


jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    environment: release
    # Allow GITHUB_TOKEN to have write permissions
    permissions:
      contents: write
    name: Merge Release Branch To Main
    steps:
      # 1. Fetch short-lived token from the GitHub App
      - name: Generate Temporary Token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # ratchet:actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.FIREBASE_RELEASE_APP_ID }}
          private-key: ${{ secrets.FIREBASE_RELEASE_APP_PRIVATE_KEY }}

      # 2. Checkout code using the dynamic token
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      # 3. Configure Git user metadata using the App's profile
      - name: Configure Git
        run: |
          git config --global user.name "firebase-release-app[bot]"
          git config --global user.email "firebase-release-app[bot]@users.noreply.github.com"

      # 4. Merge release branch
      - name: Merge release branch
        run: |
          git checkout release
          git pull origin release
          git checkout main
          git pull origin main
          git merge release --no-ff -m "(chore): Merge release into main for release $VERSION"
          git push origin master
