name: Release

on: push

jobs:
  release:
    if: github.ref == 'refs/heads/release' || endsWith(github.ref, '-releasebranch')
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Add a changeset for @firebase/app
        run: |
          git pull -f origin master:master
          yarn ts-node-script scripts/ci/add_changeset.ts

      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.OSS_BOT_GITHUB_TOKEN }}