/**
 * @license
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  FirestoreClient,
  firestoreClientDeleteAllFieldIndexes,
  firestoreClientSetFieldIndexManagementApi
} from '../core/firestore_client';
import { cast } from '../util/input_validation';
import { logDebug, logWarn } from '../util/log';

import { ensureFirestoreConfigured, Firestore } from './database';
import { FieldIndexManagementApiImpl } from '../index/field_index_management';

/**
 * A `PersistentCacheIndexManager` for configuring persistent cache indexes used
 * for local query execution.
 *
 * To use, call `getPersistentCacheIndexManager()` to get an instance.
 */
export class PersistentCacheIndexManager {
  /** A type string to uniquely identify instances of this class. */
  readonly type: 'PersistentCacheIndexManager' = 'PersistentCacheIndexManager';

  _fieldIndexManagementApi: FieldIndexManagementApiImpl | null = null;

  _fieldIndexManagementApiInstallPromise: Promise<void> | null = null;

  /** @hideconstructor */
  constructor(readonly _client: FirestoreClient) {}
}

/**
 * Returns the PersistentCache Index Manager used by the given `Firestore`
 * object.
 *
 * @return The `PersistentCacheIndexManager` instance, or `null` if local
 * persistent storage is not in use.
 */
export function getPersistentCacheIndexManager(
  firestore: Firestore
): PersistentCacheIndexManager | null {
  firestore = cast(firestore, Firestore);

  const cachedInstance = persistentCacheIndexManagerByFirestore.get(firestore);
  if (cachedInstance) {
    return cachedInstance;
  }

  const client = ensureFirestoreConfigured(firestore);
  if (client._uninitializedComponentsProvider?._offlineKind !== 'persistent') {
    return null;
  }

  const instance = new PersistentCacheIndexManager(client);
  persistentCacheIndexManagerByFirestore.set(firestore, instance);
  return instance;
}

/**
 * Enables the SDK to create persistent cache indexes automatically for local
 * query execution when the SDK believes cache indexes can help improve
 * performance.
 *
 * This feature is disabled by default.
 */
export function enablePersistentCacheIndexAutoCreation(
  indexManager: PersistentCacheIndexManager
): void {
  const client: FirestoreClient = indexManager._client;
  client.verifyNotTerminated();

  if (!indexManager._fieldIndexManagementApi) {
    indexManager._fieldIndexManagementApi = new FieldIndexManagementApiImpl();
  }

  indexManager._fieldIndexManagementApi.indexAutoCreationEnabled = true;

  if (indexManager._fieldIndexManagementApiInstallPromise) {
    return;
  }

  indexManager._fieldIndexManagementApiInstallPromise =
    firestoreClientSetFieldIndexManagementApi(
      client,
      indexManager._fieldIndexManagementApi
    )
      .then(_ => {
        logDebug('enabling persistent cache index auto creation succeeded');
      })
      .catch(error =>
        logWarn('enabling persistent cache index auto creation failed', error)
      );
}

/**
 * Stops creating persistent cache indexes automatically for local query
 * execution. The indexes which have been created by calling
 * `enablePersistentCacheIndexAutoCreation()` still take effect.
 */
export function disablePersistentCacheIndexAutoCreation(
  indexManager: PersistentCacheIndexManager
): void {
  // TODO: Refactor this code such that disabling persistent cache auto creation
  //  does _not_ need FieldIndexManagementApiImpl (i.e. it just uses the
  //  interface) so that FieldIndexManagementApiImpl can be tree-shaken away if
  //  the only client-side indexing function used is this one.
  if (indexManager._fieldIndexManagementApi) {
    indexManager._fieldIndexManagementApi.indexAutoCreationEnabled = false;
  }
}

/**
 * Removes all persistent cache indexes.
 *
 * Please note this function will also deletes indexes generated by
 * `setIndexConfiguration()`, which is deprecated.
 */
export function deleteAllPersistentCacheIndexes(
  indexManager: PersistentCacheIndexManager
): void {
  // TODO: Refactor this code such that deleting field indexes does _not_ need
  //  FieldIndexManagementApiImpl so that FieldIndexManagementApiImpl can be
  //  tree-shaken away if the only client-side indexing function used is this
  //  one.
  firestoreClientDeleteAllFieldIndexes(indexManager._client)
    .then(_ => logDebug('deleting all persistent cache indexes succeeded'))
    .catch(error =>
      logWarn('deleting all persistent cache indexes failed', error)
    );
}

/**
 * Maps `Firestore` instances to their corresponding
 * `PersistentCacheIndexManager` instances.
 *
 * Use a `WeakMap` so that the mapping will be automatically dropped when the
 * `Firestore` instance is garbage collected. This emulates a private member
 * as described in https://goo.gle/454yvug.
 */
const persistentCacheIndexManagerByFirestore = new WeakMap<
  Firestore,
  PersistentCacheIndexManager
>();

/**
 * Test-only hooks into the SDK for use exclusively by tests.
 */
export class TestingHooks {
  private constructor() {
    throw new Error('creating instances is not supported');
  }

  static setIndexAutoCreationSettings(
    indexManager: PersistentCacheIndexManager,
    settings: {
      indexAutoCreationMinCollectionSize?: number;
      relativeIndexReadCostPerDocument?: number;
    }
  ): void {
    if (!indexManager._fieldIndexManagementApi) {
      indexManager._fieldIndexManagementApi = new FieldIndexManagementApiImpl();
    }

    if (settings.indexAutoCreationMinCollectionSize !== undefined) {
      indexManager._fieldIndexManagementApi.indexAutoCreationMinCollectionSize =
        settings.indexAutoCreationMinCollectionSize;
    }
    if (settings.relativeIndexReadCostPerDocument !== undefined) {
      indexManager._fieldIndexManagementApi.relativeIndexReadCostPerDocument =
        settings.relativeIndexReadCostPerDocument;
    }
  }
}
